rongcloud:
    appkey: AAAAA
    secret: SSSSS
port: 8080
app:
    version:
        android:
            name: 1.0.0
            url: http://localhost.com/download/android
        ios:
            name: 1.0.0
            url: http://localhost.com/download/ios
